apiVersion: v1
kind: Service
metadata:
  name: add
  labels:
    service: add
    tier: backend
    transport: grpc
spec:
  ports:
  - port: 8888
  selector:
    service: add
    tier: backend
    transport: grpc
