apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 2
  template:
    metadata:
      labels:
        service: api
        tier: backend
    spec:
      containers:
      - name: apisrv
        image: vems/api-gateway:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8888
