---
name: VEMS
description: VEMS - VEMS Example MicroServices
url: http://vems.github.io
baseurl: "/vems"
timezone: America/New_York
exclude:
- Gemfile
- Gemfile.lock
- README.md
sass:
  style: :compressed
version: 1.0.0
